name: Validate

on:
  pull_request:
  workflow_call:

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  check-links:
    runs-on: ubuntu-latest
    needs: [ build ]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Restore built files
        uses: actions/cache@v4
        with:
          path: build/html
          key: build-${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}-${{ github.sha }}
          fail-on-cache-miss: true  # depend entirely on the build step

      - name: Serve doc
        run: make prod &

      - name: Check for internal dead links
        run: wget --retry-connrefused --waitretry=1 --spider --recursive --page-requisites http://localhost:8000

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Lint Markdown files
        run: make lint

      - name: Spell check
        run: make spellcheck
